//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string LicenseKey { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string HDDSerialNumber { get; set; }
        public string ProcessorID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Users { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ProductName { get; set; }
        public string ProductVersion { get; set; }
        public string ComputerName { get; set; }
        public string PublicIPAddress { get; set; }
        public string MacAddress { get; set; }
        public Nullable<int> Customer_CustomerId { get; set; }
        public string TotalInvoice { get; set; }
        public string TotalInvoiceClient { get; set; }
        public int ExpireDays { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
